name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.42
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      RAILS_ENV: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database_test
      MYSQL_DATABASE_TEST: database_test
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -P 3306 -u root -ppassword --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL is ready!"

      - name: Create test database
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS database_test;"

      - name: Debug database configuration
        run: |
          echo "Environment variables:"
          echo "RAILS_ENV: $RAILS_ENV"
          echo "MYSQL_USER: $MYSQL_USER"
          echo "MYSQL_PASSWORD: $MYSQL_PASSWORD"
          echo "MYSQL_DATABASE: $MYSQL_DATABASE"
          echo "MYSQL_HOST: $MYSQL_HOST"
          echo "MYSQL_PORT: $MYSQL_PORT"
          echo "Database configuration:"
          bundle exec rails runner "puts ActiveRecord::Base.configurations.configs_for(env_name: 'test').first.inspect"

      - name: Run database migrations
        run: bundle exec rake db:migrate RAILS_ENV=test

      - name: Run RSpec tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec rubocop
